### ISSUE TITLE
How to interpret BIBD results

### ISSUE THREAD

**Issue by ZJouba** [yangeorget/nucs#1]
Hi there,

Thanks for providing this library. I'm currently trying to implement the BIBD example on my side. 

I've solved it previously using [pycsp3](https://pycsp.org/) like so
``` python
def bibd(num_participants, block_size, lambd):
    clear()

    num_blocks = int(
        (lambd * num_participants * (num_participants - 1))
        / (block_size * (block_size - 1))
    )
    num_replicas = int((lambd * (num_participants - 1)) / (block_size - 1))

    # x[i][j] is the value of the matrix at row i and column j
    x = VarArray(size=[num_participants, num_blocks], dom={0, 1})

    satisfy(
        # constraints on rows
        [Sum(row) == num_replicas for row in x],
        # constraints on columns
        [Sum(col) == block_size for col in columns(x)],
        # scalar constraints with respect to lambda
        [row1 * row2 == lambd for row1, row2 in combinations(x, 2)],
        # Increasingly ordering both rows and columns  tag(symmetry-breaking)
        LexIncreasing(x, matrix=True),
    )

    if solve() is SAT:
        return values(columns(x))
```
Which for `BIBD(8, 4, 3)` provides the output as follows:
``` json
[
	[0, 0, 0, 0, 1, 1, 1, 1], 
	[0, 0, 1, 1, 0, 0, 1, 1], 
	[0, 0, 1, 1, 0, 1, 0, 1], 
	[0, 1, 0, 0, 1, 1, 0, 1], 
	[0, 1, 0, 1, 0, 1, 1, 0], 
	[0, 1, 1, 0, 1, 0, 1, 0], 
	[0, 1, 1, 1, 1, 0, 0, 0], 
	[1, 0, 0, 1, 1, 0, 1, 0], 
	[1, 0, 0, 1, 1, 1, 0, 0], 
	[1, 0, 1, 0, 0, 1, 1, 0], 
	[1, 0, 1, 0, 1, 0, 0, 1], 
	[1, 1, 0, 0, 0, 0, 1, 1], 
	[1, 1, 0, 1, 0, 0, 0, 1], 
	[1, 1, 1, 0, 0, 1, 0, 0]
]
```

However, when I apply it to the example:
``` python
def bibd(num_participants, block_size, lambd):
    num_blocks = int(
        (lambd * num_participants * (num_participants - 1))
        / (block_size * (block_size - 1))
    )
    num_replicas = int((lambd * (num_participants - 1)) / (block_size - 1))

    n = (
        num_participants + ((num_participants * (num_participants - 1)) // 2)
    ) * num_blocks

    problem = Problem([(0, 1)] * n)

    for row in range(0, num_participants):
        problem.add_propagator(
            (
                list(range(row * num_blocks, (row + 1) * num_blocks)),
                ALG_EXACTLY_EQ,
                [1, num_replicas],
            )
        )

    for col in range(0, num_blocks):
        problem.add_propagator(
            (
                list(range(col, num_participants * num_blocks, num_blocks)),
                ALG_EXACTLY_EQ,
                [1, block_size],
            )
        )

    conj_idx = num_participants * num_blocks
    for i1 in range(0, num_participants - 1):
        for i2 in range(i1 + 1, num_participants):
            conj_vars = []
            for j in range(0, num_blocks):
                problem.add_propagator(
                    (
                        [(i1 * num_blocks + j), (i2 * num_blocks + j), conj_idx],
                        ALG_MIN_EQ,
                        [],
                    )
                )
                conj_vars.append(conj_idx)
                conj_idx += 1
            problem.add_propagator((conj_vars, ALG_EXACTLY_EQ, [1, lambd]))

    for i in range(0, num_participants - 1):
        problem.add_propagator(
            (
                list(range(i * num_blocks, (i + 2) * num_blocks)),
                ALG_LEXICOGRAPHIC_LEQ,
                [],
            )
        )

    for j in range(0, num_blocks - 1):
        problem.add_propagator(
            (
                list(range(j, num_participants * num_blocks, num_blocks))
                + list(range(j + 1, num_participants * num_blocks, num_blocks)),
                ALG_LEXICOGRAPHIC_LEQ,
                [],
            )
        )

    solver = BacktrackSolver(problem)
    result = solver.solve_one()
```
I do not know how to interpret the `result` which is a list of 0 and 1 with length 504.

Any help would be appreciated

**Comment by yangeorget** [comment]
Hello,

Thank you very much for your question. 

I have updated the model for the BIBD problem by : renaming the variables and adding a **solution_as_matrix** function.
Having the solution as a matrix makes it possible to print it.
You will find an example where I use this new function to print the solutions 
 here: https://github.com/yangeorget/nucs/blob/main/nucs/examples/bibd/__main__.py

Please let me know if things are clearer now. 
If not, I can help...

Best regards,
Yan

**Comment by yangeorget** [comment]
I'd also like to know how you discovered NUCS on the web.

**Comment by ZJouba** [comment]
Thanks @yangeorget, I'm still a little confused but it's working. Unfortunately, it doesn't seem to run faster than when using the CPU. I really thought it would be so much faster.

I came accross NUCS when googling to try and find a CUDA optimised constraint solver. This is the actual Google search from my history:
https://www.google.com/search?sca_esv=4c0b7159feae1cdb&sca_upv=1&rlz=1C1CHZN_enZA1107ZA1107&sxsrf=ADLYWIL4PyYqxGQJuoKvkss_BNATYgB91A:1727701395765&q=%22Numba%22+%22BIBD%22&sa=X&ved=2ahUKEwihyeOf3eqIAxUHQ6QEHaHxFf4Q5t4CegQIFxAB&biw=1920&bih=911&dpr=1

**Comment by yangeorget** [comment]
Hello @ZJouba,

Several things:
1/ _I'm still a little confused_ :  If you tell me what's not yet clear, I might be able to help. 
2/ CUDA : NUCS does not leverage CUDA (yet), sorry for the confusion.
3/ BIBD : What are your expectations ? Are you specifically interested in the BIBD problem ? If yes, then maybe we can improve the modelling of the problem. Or is it just a random example ?

Best regards,
Yan

**Comment by ZJouba** [comment]
Thanks for the patience and help @yangeorget.

1.a. I don't understand how we map the domain from a `num_participants` x `num_blocks` array to a `Problem([(0,10], n)` domain.
1.b. I'm not grasping how the constraints work. I cannot seem to understand how they map from the pycsp3 implementation to nucs

2. NUCS uses Numba though and Numba uses CUDA?

3. It's BIBDs specifically. I need to build a database of BIBD(i, 4, 3) solutions for `8 <= i <= 100` where `i == 0 or 1 (mod 4)` and trying to find a faster way of generating them all

**Comment by yangeorget** [comment]
1a : There are two versions of the BIBD problem. The one I am using has the parameters v, b, r, k, l. It is a bit silly because the variables are not free but it is the most commonly used. There is also the version you are using with 3 free variables. You can have more details here : https://en.wikipedia.org/wiki/Block_design. The problem you are trying to solve translates into i, i(i-1)/4, i-1, 4,3 I think.

1b The modelling I am using is very common (for the 5 variables). See also: https://www.csplib.org/Problems/prob028/models/.

2 NuCS uses Numba for just-in-time compilation. Nothing has been done to leverage CUDA and GPUs.

3 With i=100, this is a very large matrix and thus a very large problem for constraint programming. Are you looking for all the solutions or just a single one for each value of i ?

**Comment by ZJouba** [comment]
Just a single one for each value of i

**Comment by yangeorget** [comment]
When I run this code:
from timeit import default_timer as timer

from rich import print

from nucs.examples.bibd.bibd_problem import BIBDProblem
from nucs.solvers.backtrack_solver import BacktrackSolver

if __name__ == "__main__":
    for i in range(8, 100):
        if i % 4 in [0, 1]:
            problem = BIBDProblem(i, (i * (i - 1)) // 4, i - 1, 4, 3)
            solver = BacktrackSolver(problem)
            start = timer()
            solver.solve_one()
            end = timer()
            print(f"{i} solved in {end - start} seconds")

I rapidly get the 2 first solutions:
8 solved in 0.031779624998307554 seconds
9 solved in 0.1582064590002119 seconds
But the 3rd is not found after hours ... 

I think that the BIBD model can be greatly improved with a constraint/propagator which is already in my TODO list : the Global Cardinality Constraint

I can spent some time implementing it this week or next one.

Cheers,
Yan

**Comment by yangeorget** [comment]
But it won't be sufficient for solving the case where i=100.
For i=100, we have a 247500 decision variables.
This means a search space of 2ˆ247500.

**Comment by ZJouba** [comment]
That's interesting. With the `pyscp` solution, I've managed to find solutions for 8, 9, 12, 13, 16, 17 and 20 within hours. But after 20 things start taking days to find solutions. Wish I had access to an HPC 😢

**Comment by yangeorget** [comment]
Hello @ZJouba,

Just a head up, I can now solve i=12 in seconds and i=13 in minutes.
I have not tried with larger i.
When I have time, I will implement GCC, it should have a big impact.
I will let you know.

Could you please start this repo ... this is important for its visibility.

Thank you

**Comment by ZJouba** [comment]
Done! Thanks @yangeorget
