### ISSUE TITLE
Write an article comparing performance with other solvers 

### ISSUE THREAD

**Issue by yangeorget** [yangeorget/nucs#12]

**Comment by ofek** [comment]
I'm extremely interested in seeing this! Have you tried solving shift scheduling problems?

**Comment by ofek** [comment]
Basically this https://developers.google.com/optimization/scheduling/employee_scheduling

**Comment by yangeorget** [comment]
Hello @ofek, Google's employee scheduling example is now implemented as an example. If you wish to have clarifications or discuss this further, don't hesitate to send me an email.

**Comment by yangeorget** [comment]
When I have time, I'll work on a faster version.

**Comment by yangeorget** [comment]
Hello @ofek, I am back from vacation and update the employee scheduling example. It is now only twice slower than the similar implementation with OR-tools.

**Comment by ofek** [comment]
That's a big improvement, nice!
